# Site settings
title: Renata Ribeiro
description: My Personal Website
baseurl: "" 
# the subpath of your site, e.g. /blog
url: "https://renaderibeiro.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Renata Ribeiro
user_description: I\'m a Computer Science Undergrad Student in UFBA. Also I hold a Bachelor's Degree in Science and Tech at the same University. I\'m an enthusiast of gender equity in science and technology. I\'m also interested in researching and teaching in technology-related fields. Areas of interest include Free Software and Hardware, Data Science, Artificial Intelligence, and Information Security.
user_title: Computer Science Undegrad Student
email: renatalrdesena@gmail.com
twitter_username: renaderibeiro
github_username:  renaderibeiro
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
